# Detailed Mathematical Explanation of SVD

- **Matrix Factorization:** SVD is a method of decomposing a matrix $A$ into three matrices $U$, $\Sigma$, and $V^T$ such that:
  $$  A = U \Sigma V^T $$
  
  
  where:
  - $U$ is an $m \times m$ orthogonal matrix whose columns are the left singular vectors of $A$.
  - $\Sigma$ is an $m \times n$ diagonal matrix with non-negative real numbers on the diagonal, known as singular values.
  - $V^T$ is the transpose of an $n \times n$ orthogonal matrix whose columns are the right singular vectors of $A$.

- **Orthogonality of $U$ and $V$:**
  - The columns of $U$ and $V$ are orthonormal, meaning that $U^T U = I$ and $V^T V = I$, where $I$ denotes the identity matrix.


- **Singular Values:**
  - The diagonal entries of $\Sigma$ are called the singular values of $A$ and are denoted by $\sigma_1, \sigma_2, \dots, \sigma_r$ (with $r \leq \min(m, n)$). These are ordered such that $\sigma_1 \geq \sigma_2 \geq \dots \geq \sigma_r \geq 0$.
  - Singular values provide insights into the "strength" or "importance" of the corresponding singular vectors in the matrix structure.


- **Geometric Interpretation:**
  - The transformation $A$ can be seen as stretching the unit sphere into an ellipsoid in $R^n$, where the singular values are the lengths of the semi-axes of the ellipsoid.

## Notes:
- Understanding SVD involves recognizing how a matrix can be broken down into simpler, meaningful components. Each component $U$, $\Sigma$, and $V^T$ has a distinct role in transforming data.
- The singular values in $\Sigma$ represent the magnitude of each axis of the transformation, showing the importance of each dimension in the dataset.
- This decomposition is particularly powerful because it reveals not just how data is structured but also the inherent relationships within the data, making it invaluable for complex data analyses and applications like compression, noise reduction, and more.


## Step-by-Step SVD Decomposition Using NumPy

In [29]:
import numpy as np

In [46]:
# Define the matrix that you want to decompose.
# A = np.array([[1, 2], [3, 4], [5, 6]])
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

## Step-by-Step SVD Decomposition Using NumPy

1. **Import NumPy Library**

In [47]:
import numpy as np

2. **Create a Matrix**
   Define the matrix that you want to decompose.

In [48]:
# A = np.array([[1, 2], [3, 4], [5, 6]])
A = np.array([[1, 2, 3], [4, 5, 6]])

3. **Compute Transpose and Multiplication**
   Compute $ A^T A $ and $AA^T$ which are needed to find the right and left singular vectors.

In [49]:
ATA = np.dot(A.T, A)
AAT = np.dot(A, A.T)

4. **Eigenvalue Decomposition**
   Perform eigenvalue decomposition on $ A^T A $ and $ AA^T $.

In [50]:
e_vals, e_vecs = np.linalg.eig(ATA)
u_vals, u_vecs = np.linalg.eig(AAT)

5. **Sort Eigenvalues and Eigenvectors**
   The singular values are the square roots of the eigenvalues of $A^T A$. Sort them (and corresponding vectors) by magnitude in descending order.


In [51]:
sorted_indices = np.argsort(e_vals)[::-1]
e_vals = e_vals[sorted_indices]
e_vecs = e_vecs[:, sorted_indices]

singular_values = np.sqrt(e_vals)

C:\Users\Prashant\AppData\Local\Temp\ipykernel_27568\2894977744.py:5: RuntimeWarning: invalid value encountered in sqrt
  singular_values = np.sqrt(e_vals)


6. **Form Diagonal Matrix $\Sigma$**
   Create $\Sigma$ from the sorted singular values.
   

In [52]:
Sigma = np.zeros(A.shape)
np.fill_diagonal(Sigma, singular_values)

In [53]:
Sigma

array([[9.508032  , 0.        , 0.        ],
       [0.        , 0.77286964, 0.        ]])

7. **Compute $V$ and $ U $ Matrices**
   Ensure the left singular vectors (U) are normalized.
   

In [54]:
U = u_vecs
V = e_vecs
U,  V

(array([[-0.92236578, -0.3863177 ],
        [ 0.3863177 , -0.92236578]]),
 array([[-0.42866713, -0.80596391,  0.40824829],
        [-0.56630692, -0.11238241, -0.81649658],
        [-0.7039467 ,  0.58119908,  0.40824829]]))

8. **Reconstruct Original Matrix**
   Verify the decomposition by reconstructing $ A $.

In [55]:
A_reconstructed = np.dot(U, np.dot(Sigma, V.T))

# Using SciPy for SVD

Using SciPy, the SVD process is much more straightforward and handles numerical stability better.

1. **Import SciPy Library**

In [56]:
from scipy.linalg import svd

2. **Perform SVD**
   Directly apply the SVD function.
   

In [57]:
U, s, VT = svd(A)

3. **Form Diagonal Matrix $\Sigma$ from s**

In [58]:
Sigma = np.diag(s)

4. **Reconstruct Original Matrix**
   Use the U, Sigma, and VT matrices to reconstruct $ A $.

In [59]:
A_reconstructed = np.dot(U, np.dot(Sigma, VT))

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

The error you're encountering occurs because the dimensions of the matrices involved in the matrix multiplication are not aligned properly. This is a common issue when reconstructing matrices from their SVD components, particularly when the original matrix $ A $ is not square (i.e., $ m \neq n $).

In SVD, $ U $, $ \Sigma $, and $ V^T $ have specific shapes:
- $ U $ is $ m \times m $,
- $ \Sigma $ (as returned by `svd` in its minimal form) is $ \min(m, n) \times \min(m, n) $,
- $ V^T $ is $ n \times n $.

For a non-square $ A $ of size $ m \times n $:
- If $ m > n $, $ \Sigma $ will be smaller than $ U $ in one dimension and smaller than $ V^T $ in the other, meaning direct multiplication won't work because of mismatched dimensions.

Here's how you can fix this:

### Correct Reconstruction for Non-Square Matrices Using NumPy

If you have used `scipy.linalg.svd` and retained the minimal $ \Sigma $ (which is typically a 1D array of singular values), you need to construct the full $ \Sigma $ matrix properly to match the dimensions of $ U $ and $ V^T $.

Here’s the revised approach:

In [60]:
import numpy as np
from scipy.linalg import svd

# Example non-square matrix
# A = np.array([[1, 2], [3, 4], [5, 6]])
A = np.array([[1, 2, 3], [4, 5, 6]])

In [61]:
# Perform SVD
U, s, VT = svd(A, full_matrices=False)

In [62]:
# Construct full Sigma matrix with correct dimensions
Sigma = np.zeros((U.shape[1], VT.shape[0]))
np.fill_diagonal(Sigma, s)

In [63]:
# Reconstruct original matrix
A_reconstructed = np.dot(U, np.dot(Sigma, VT))

print(A_reconstructed)

[[1. 2. 3.]
 [4. 5. 6.]]


### Key Adjustments:

1. **`full_matrices=False` in `svd` function**: This ensures that $ U $ and $ V^T $ are returned in reduced form, i.e., $ U $ will be $ m \times \min(m, n) $ and $ V^T $ will be $ \min(m, n) \times n $.
2. **Constructing $ \Sigma $**: Instead of using `np.diag(s)`, which only works if $ m = n $, the code now initializes $ \Sigma $ as a zero matrix of appropriate size and fills its diagonal with the singular values stored in `s`. This matches $ \Sigma $'s dimensions correctly with those of $ U $ and $ V^T $ for matrix multiplication.

This method should resolve the dimension mismatch and successfully reconstruct the original matrix $ A $ from its SVD components.

# Orthogonal Matrices

### Definition of Orthogonal Matrices

An **orthogonal matrix** is a square matrix $ Q $ whose columns and rows are orthogonal unit vectors (orthonormal vectors). In simpler terms, this means that when a matrix is orthogonal, multiplying it by its transpose results in the identity matrix. Mathematically, this is represented as:
$$ Q^T Q = Q Q^T = I $$
where $ Q^T $ is the transpose of $ Q $, and $ I $ is the identity matrix of appropriate size.

### Important Properties of Orthogonal Matrices

1. **Preservation of Length (Norm):**
   - Orthogonal transformations (represented by orthogonal matrices) preserve the length (norm) of vectors. If $ \mathbf{v} $ is any vector, then $ \| Q\mathbf{v} \| = \| \mathbf{v} \| $. This property is crucial in many applications, including those in computer graphics and numerical methods, where maintaining the original length of vectors during transformations is necessary.

2. **Preservation of Angle:**
   - Orthogonal matrices preserve the angles between vectors. If $ \mathbf{u} $ and $ \mathbf{v} $ are vectors, then the angle between $ Q\mathbf{u} $ and $ Q\mathbf{v} $ is the same as the angle between $ \mathbf{u} $ and $ \mathbf{v} $. This is particularly useful in preserving the geometric properties of figures during transformations.

3. **Inverse is Equal to Transpose:**
   - The inverse of an orthogonal matrix is equal to its transpose: $ Q^{-1} = Q^T $. This simplifies computations involving matrix inversions, as calculating the transpose is generally more straightforward and computationally cheaper than finding the inverse.

4. **Determinant Values:**
   - The determinant of an orthogonal matrix is always $ \pm 1 $. This arises from the property that the product of the eigenvalues (which are all $ \pm 1 $ for orthogonal matrices) equals the determinant. The sign $ +1 $ indicates a rotation while $ -1 $ indicates a reflection combined with a rotation.

5. **Stability in Numerical Computations:**
   - Orthogonal matrices are numerically stable in computations, which makes them valuable in complex numerical calculations where minimizing error propagation is critical. For example, in algorithms like QR factorization used in solving linear systems, eigenvalue computations, and more.

6. **Eigenvalues on the Unit Circle:**
   - The eigenvalues of an orthogonal matrix lie on the unit circle in the complex plane. This means their absolute values are 1, reflecting the preservation of vector norms.

### Applications

Orthogonal matrices are widely used across various fields such as physics, engineering, computer graphics, and statistics. They are pivotal in transformations that require maintaining the original structure of data, such as rotations in space, reflecting shapes, and changing bases in vector spaces without distorting the vector magnitudes or angles.
