In [ ]:
import numpy as np
from scipy.linalg import lu

In [ ]:
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])

In [ ]:
P, L, U = lu(A)

In [ ]:
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L:
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]
U:
 [[ 2.   1.   1. ]
 [ 0.   2.5  1.5]
 [ 0.   0.  -0.2]]


## Reconstruct A Using Matrix Multiplication

In [ ]:
A_reconstructed = np.dot(P, np.dot(L, U))

In [ ]:
print("Reconstructed A:\n", A_reconstructed)

Reconstructed A:
 [[ 2.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  3.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00 -2.77555756e-17]]


# Spectral decomposition

Spectral decomposition, also known as eigenvalue decomposition, is a fundamental concept in linear algebra, particularly relevant to symmetric (or Hermitian in the complex case) matrices.

It plays a critical role in many areas of mathematics, physics, engineering, and data science, especially in tasks involving principal component analysis, quantum mechanics, and various signal processing techniques.

### Definition and Overview

Spectral decomposition involves decomposing a matrix into a set of eigenvectors and eigenvalues. For a given square matrix $ A $, if $ A $ is symmetric, the spectral decomposition expresses $ A $ as:

$ A = Q \Lambda Q^T $

where:
- $ Q $ is a matrix whose columns are the eigenvectors of $ A $.
- $ \Lambda $ is a diagonal matrix whose diagonal elements are the corresponding eigenvalues.
- $ Q^T $ is the transpose of $ Q $.

The key requirement here is that $ A $ must be symmetric, meaning $ A = A^T $. This condition guarantees that $ A $ has real eigenvalues and its eigenvectors are orthogonal.

### Properties of Spectral Decomposition

1. **Orthogonality of Eigenvectors**: The matrix $ Q $ is an orthogonal matrix. This means that the eigenvectors are not only linearly independent but also orthogonal to each other.

2. **Diagonalizability**: A symmetric matrix $ A $ is always diagonalizable, meaning it can be expressed as the product of its eigenvectors and eigenvalues matrices as described above. This property stems from the fact that symmetric matrices do not have complex eigenvalues and their eigenvectors can be chosen orthogonally.

3. **Reconstruction**: Given the eigenvectors and eigenvalues, the original matrix $ A $ can be reconstructed using the formula $ A = Q \Lambda Q^T $.

4. **Stability**: The spectral decomposition is numerically stable, making it a preferred method for numerical computations that involve eigenvalues and eigenvectors.

### Applications in Data Science and Real World

- **Principal Component Analysis (PCA)**: In data science, spectral decomposition is used to perform PCA, which is a technique to reduce the dimensionality of data while retaining those characteristics of the dataset that contribute most to its variance, by keeping lower-order principal components and ignoring higher-order ones.
  
- **Vibration Analysis**: In engineering, spectral decomposition is used to understand the vibration modes of a structure. Each eigenvalue can represent a natural frequency, and each eigenvector represents a mode shape of the structure under those frequencies.

- **Quantum Mechanics**: In physics, particularly in quantum mechanics, spectral decomposition is used to solve the Schrödinger equation. The eigenvalues represent the energy levels and the eigenvectors represent the state vectors of the system.

- **Image Compression**: Spectral decomposition is also used in image compression techniques. By decomposing an image matrix into its spectral components, one can keep the most significant features (associated with larger eigenvalues) and achieve effective compression.

Spectral decomposition thus serves as a powerful tool in both theoretical analyses and practical applications across various scientific and engineering disciplines.


In [ ]:
import numpy as np
from numpy.linalg import eigh

In [ ]:
# Step 2: Define a symmetric matrix
# We create a symmetric matrix A
A = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]])

In [ ]:
# Step 3: Perform the spectral decomposition
# eigh returns the eigenvalues and eigenvectors of a Hermitian or symmetric matrix
eigenvalues, eigenvectors = eigh(A)

In [ ]:
# Step 4: Verify the decomposition
# Reconstruct the original matrix
A_reconstructed = eigenvectors @ np.diag(eigenvalues) @ eigenvectors.T

In [ ]:
# Print results
print("Original Matrix A:\n", A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("Reconstructed Matrix A:\n", A_reconstructed)

Original Matrix A:
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
Eigenvalues:
 [0.58578644 2.         3.41421356]
Eigenvectors:
 [[ 5.00000000e-01 -7.07106781e-01 -5.00000000e-01]
 [ 7.07106781e-01  4.88509860e-17  7.07106781e-01]
 [ 5.00000000e-01  7.07106781e-01 -5.00000000e-01]]
Reconstructed Matrix A:
 [[ 2.00000000e+00 -1.00000000e+00 -1.40750406e-16]
 [-1.00000000e+00  2.00000000e+00 -1.00000000e+00]
 [-6.22457832e-17 -1.00000000e+00  2.00000000e+00]]


# Comparison of Decomposition Methods

Spectral decomposition, LU decomposition, and Singular Value Decomposition (SVD) are all matrix decomposition techniques used in linear algebra, but they differ in their methods, requirements, and applications. Understanding these differences can help clarify when to use each type of decomposition.

### Spectral Decomposition (Eigenvalue Decomposition)
- **Applicability**: Spectral decomposition is specifically applicable to square, symmetric matrices (or Hermitian in the complex case). It cannot be used for non-square or non-symmetric matrices.
- **Decomposition**: It decomposes a matrix \( A \) into \( Q \Lambda Q^T \), where \( Q \) is an orthogonal matrix whose columns are the eigenvectors of \( A \), and \( \Lambda \) is a diagonal matrix containing the eigenvalues of \( A \).
- **Properties**: The matrix \( A \) must be symmetric, ensuring that all eigenvalues are real and the eigenvectors are orthogonal.
- **Use Cases**: Often used in scenarios involving optimization, quadratic forms, differential equations, and PCA where the matrix symmetry is assured.

### LU Decomposition
- **Applicability**: LU decomposition can be applied to any square matrix, and extended forms like LDU or PLU can handle non-square matrices.
- **Decomposition**: It factorizes a matrix \( A \) into \( P, L, \) and \( U \) where \( P \) is a permutation matrix, \( L \) is a lower triangular matrix with unit diagonal elements, and \( U \) is an upper triangular matrix.
- **Properties**: It does not require the matrix \( A \) to be symmetric and is a fundamental method used for solving linear equations and matrix inversion.
- **Use Cases**: Commonly used in numerical solutions of systems of linear equations, where direct methods are applicable.

### Singular Value Decomposition (SVD)
- **Applicability**: SVD can be applied to any \( m \times n \) matrix, regardless of its properties of symmetry or square shape.
- **Decomposition**: It decomposes a matrix \( A \) into \( U, \Sigma, \) and \( V^T \), where \( U \) and \( V \) are orthogonal matrices, and \( \Sigma \) is a diagonal matrix (not necessarily square) containing the singular values.
- **Properties**: SVD is more general and robust, providing a decomposition even when \( A \) is not square or symmetric. The singular values in \( \Sigma \) provide insights into the "effect" or "impact" of the corresponding singular vectors.
- **Use Cases**: Extensively used in signal processing, statistics, pattern recognition, and data reduction techniques like PCA. SVD is invaluable for problems involving pseudoinverse, least squares fitting, and condition number estimation.

### Key Differences
- **Generality**: SVD is the most general form of decomposition, applicable to all matrices, while spectral decomposition is the most restrictive, limited only to square, symmetric matrices. LU sits in between, applicable to square matrices and extendable to non-square matrices.
- **Orthogonality**: Both SVD and spectral decomposition involve orthogonal matrices (in eigenvector and singular vector matrices), which preserve angles and lengths, unlike LU decomposition, which is merely a triangular decomposition without orthogonality constraints.
- **Mathematical Properties**: Spectral decomposition and SVD provide valuable insights into the geometric and statistical properties of the matrix (via eigenvalues and singular values), which are not directly obtainable from LU decomposition.

Each decomposition has its place depending on the matrix properties and the specific requirements of the application, such as the need for solving systems of equations (LU), understanding intrinsic dimensional properties of data (SVD), or simplifying matrix operations in symmetric matrices (spectral decomposition).